# Generated by Django 6.0.5 on 2026-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_apikey_key_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_full',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
